### PR TITLE
Fix elements order

### PR DESCRIPTION
**Pull request by YAY-C**

### CODE REVIEW

**Comment by YAY-C** [comment]
I also fixed the name of the output file when generating `spin=0`  (open-shell like) representations

**Comment by briling** [comment]
Thanks!
> I think we should keep it consistent! Inside the function (and not in the main) seems better I think.
In the function is better I guess if it's possible to rewrite for the bond one
> _Should I include it in this issue ? or create a new one ?_
It should be a new one, this is a different problem

**Comment by briling** [comment]
do we always sort elements for spahm-b?

**Comment by briling** [comment]
okay I think for spahm-b doesn't matter since we sort atom pairs anyway https://github.com/lcmd-epfl/Q-stack/blob/master/qstack/spahm/rho/dmb_rep_bond.py#L73-L74

**Pull request merged**
